### ISSUE TITLE
Unhandled Promise Error 

### ISSUE THREAD

**Issue by gonsie** [Gaurav-Shankar/check-username#3]
Cool tool! I found you through dev.to. Unfortunately, I'm running into the following unhandled error which causes the program to crash:
```
Checking username: gonsie
Checking : instagram.com
(node:32295) UnhandledPromiseRejectionWarning: FetchError: request to https://www.instagram.com/gonsie failed, reason: self signed certificate in certificate chain
    at ClientRequest.<anonymous> (/Users/gonsiorowski1/homebrew/lib/node_modules/unique-username/node_modules/node-fetch/lib/index.js:1430:11)
    at ClientRequest.emit (events.js:197:13)
    at TLSSocket.socketErrorListener (_http_client.js:399:9)
    at TLSSocket.emit (events.js:197:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
(node:32295) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:32295) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Probably due to my company's firewall... but this tool could fail more gracefully.

Thanks!

**Comment by Gaurav-Shankar** [comment]
@gonsie Great, thanks for pointing out. I'll fix it.

Meanwhile, you might wanna check out these API for the same purpose:
1. https://check-user-api.herokuapp.com/api/v1/getServiceNames
2. https://check-user-api.herokuapp.com/api/v1/{servicename}/{username}

**Comment by Gaurav-Shankar** [comment]
@aoneill01 would you want to work on this one?

**Comment by aoneill01** [comment]
@Gaurav-Shankar - Yeah, I have an idea. I'll take a look at it.

**Comment by Gaurav-Shankar** [comment]
@gonsie Can you please update the npm package and confirm if the issue is fixed?

**Comment by gonsie** [comment]
worked for me!
